### ISSUE TITLE
Error while launching this stack

### ISSUE THREAD

**Issue by krishnamee2004** [awslabs/cost-optimization-ec2-right-sizing#1]
While launching the stack, I received the following error:

![image](https://cloud.githubusercontent.com/assets/4068287/20115804/b2092d6c-a5c7-11e6-9807-2971b3d20aea.png)

It looks like the error is coming from here:

![image](https://cloud.githubusercontent.com/assets/4068287/20115782/9ecf1bc6-a5c7-11e6-9ba4-41d9b71fa73d.png)

**Comment by milbrya** [comment]
You are seeing this error because Fn:Select is trying to reference an index in an array/list that does not exist. 

Now WHY you are getting this error is a larger issue that requires a bit of digging around. We need to figure out why a result from Fn:GetAZs is returning a result without a value at index position 1. 

Can you please get back to us on the following:
- What region are you running this in where you see the error?
- Can you please run "aws ec2 describe-availability-zones" in the same region you are launching the stack and give us the output?
- Try changing the index in the Fn:Select from 1 to 0 and update/re-launch the stack. Do you get the same error or a different error (i.e. do you now get "Availability Zone cannot be null")? Please make sure that you change all of the occurrences in the template.
